#
# Aeon Digital
# Rianna Cantarelli <rianna@aeondigital.com.br>
#
.SILENT:




#
# Mostra um help
help:
	make/makeActions.sh makeExecuteBefore "$@"
	Shell-Make/modules/help/makeActions.sh makeHelp
	make/makeActions.sh makeExecuteAfter "$@"